### ISSUE TITLE
Is there a way to wire in abbrev?

### ISSUE THREAD

**Issue by aikrahguzar** [astoff/jit-spell#10]
Hi,
  Thanks for this package, I just tried it and it works very well. Inspired by this [blog post](http://endlessparentheses.com/ispell-and-abbrev-the-perfect-auto-correct.html). I have been using something similar to add words to the global abbrev table whenever I correct a word and I like this since I think it is better if Emacs learns from my mistakes instead of me :)

Is there a way to achieve this easily with `jit-spell`? From a cursory glance I can't see any but I can see a few ways of enabling this behavior:

1) Right now `jit-spell-correct-word` seems to return `nil`, maybe it can be made to return to return a list of conses the `car` of which is the corrected word and the `cdr` is the correction. This will make it easy to define a new command that wraps `jit-spell-correct-word` and adds to the abbrev table.

2) Provide an abnormal hook that takes the corrected word and correction as arguments. I don't actually see much use for such a hook but it will do the job.

3) Refactor `jit-spell-correct-word` to do the correction in a function that takes the region of misspelling as the argument and does the correction. This function can then be advised.

Thanks again!

**Comment by astoff** [comment]
Option 3 is already provided, see `jit-spell--apply-correction`.

You seem to suggest this feature should be relegated to the users able to hack into Lisp code, and at first sight I guess I agree. Let me know otherwise.

**Comment by aikrahguzar** [comment]
> Option 3 is already provided, see `jit-spell--apply-correction`.
> 
> You seem to suggest this feature should be relegated to the users able to hack into Lisp code, and at first sight I guess I agree. Let me know otherwise.

I will be happy if you decide to provide this feature but I feel it is too niche for that. I think it is enough if it can be put somewhere so people who don't want to hack elisp themselves can copy paste. So I will leave my solution here:
```emacs-lisp
(advice-add #'jit-spell--apply-correction :before
              (defun +jit-spell-save-to-abbrev (ov correction)
                (let ((misspelling (buffer-substring-no-properties (overlay-start ov) (overlay-end ov))))
                  (define-abbrev global-abbrev-table misspelling correction)
                  (message "\"%s\" now expands to \"%s\" globally" misspelling correction))))
```
Thanks a lot for the package!
