### ISSUE TITLE
jit-lock-function signaled an error

### ISSUE THREAD

**Issue by texaco** [astoff/jit-spell#12]
I have installed without a problem 'jit-spell´ on a linux system with a built from source emacs. But when I install it on a emacs (28.2) on macos (from emacsformacosx.com) it does not work.

- No font giving feedback about mispelled word
- Message buffer littered with "Error during redisplay: (jit-lock-function XXXX) signaled (wrong-number-of-arguments #<subr plist-get> 3) (being XXXX different number which I believe is the character possition where to start rendering the fontification)

This error is also happening starting emacs with -Q flag.

Let me know if i can provide more information but I have tried 'toggle-debug-on-error' and 'debug-on-entry' on jit-lock-function without any luck.

For more information it works with flyspell.

Thanks for the package which seems very promising!

**Comment by astoff** [comment]
Thanks for the heads up, should be fixed now (so far only in the git repo, not ELPA).
