### ISSUE TITLE
ignored faces for org-mode

### ISSUE THREAD

**Issue by zzkt** [astoff/jit-spell#7]
Not sure if you are planning to include more mode specific defaults or leave it up to the user.  Either way, this simple list of faces to ignore in org-mode buffers has been useful...

```
org-block-begin-line 
org-block-end-line 
org-meta-line 
org-block
```

**Comment by astoff** [comment]
This should be working as of jit-spell v0.2. If you still see some minor glitches, it's an issue in Org's own `org-mode-flyspell-verify` function, which you could report to them.
